spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Gyb285458125
    url: jdbc:mysql://db:3306/springCloud_order?characterEncoding=utf-8&useSSL=false
