spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Gyb285458125
    url: jdbc:mysql://db:3306/springCloud_product?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
    defaultZone: http://localhost:8761/eureka/
