spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: carl
    password: hzcr8888
    url: jdbc:mysql://localhost:3306/SpringCloud_user?charactorEncoding=utf-8&useSSL=false
  redis:
    host: localhost
    port: 6379
